theme: jekyll-theme-minimal
title: Angular course
description: Angular course, with HTML5, CSS and Typescript, including a small Angular project 
logo: logo-nav@2x.png
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]